# Generated by Django 5.2.17 on 2026-10-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0003_llm_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="Keyed hash of the visitor's IP, for abuse checks",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Sandbox organization created for this upload alone",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="try_submission",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
