# Generated by Django 5.2.17 on 2026-10-03 10:45

import apps.rates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0003_llm_usage"),
        ("shipments", "0003_issue_amount_at_risk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedAccessorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=200)),
                (
                    "vendor_key",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("detention", "Detention"),
                            ("demurrage", "Demurrage"),
                            ("storage", "Storage"),
                            ("per_diem", "Per diem"),
                            ("waiting_time", "Waiting time"),
                            ("redelivery", "Re-delivery or dry run"),
                            ("exam", "Customs exam or inspection"),
                            ("congestion", "Congestion or peak season surcharge"),
                            ("admin_fee", "Admin fee"),
                            ("pre_pull", "Pre-pull"),
                            ("chassis_split", "Chassis split"),
                            ("overweight", "Overweight surcharge"),
                            ("hazmat", "Hazardous cargo surcharge"),
                            ("other", "Other charge"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("day", "Per day"),
                            ("hour", "Per hour"),
                            ("each", "Per occurrence"),
                        ],
                        default="each",
                        max_length=8,
                    ),
                ),
                (
                    "free_units",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Free days or hours before the charge starts",
                    ),
                ),
                (
                    "max_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Most the vendor may charge per day, hour or occurrence",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Most the vendor may charge in total on one invoice",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_accessorials",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["vendor_name", "code", "-valid_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=200)),
                (
                    "vendor_key",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="The vendor's quote or contract number",
                        max_length=60,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        help_text="Port of loading. Empty = any origin",
                        max_length=120,
                    ),
                ),
                (
                    "origin_key",
                    models.CharField(blank=True, editable=False, max_length=60),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="Port of discharge. Empty = any destination",
                        max_length=120,
                    ),
                ),
                (
                    "destination_key",
                    models.CharField(blank=True, editable=False, max_length=60),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any equipment"),
                            ("20GP", "20' standard (20GP)"),
                            ("40GP", "40' standard (40GP)"),
                            ("40HC", "40' high cube (40HC)"),
                            ("45HC", "45' high cube (45HC)"),
                            ("20RF", "20' reefer (20RF)"),
                            ("40RF", "40' reefer (40RF)"),
                            ("LCL", "Less than container load (LCL)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("valid_from", models.DateField()),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, help_text="Empty = no end date", null=True
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "all_in",
                    models.BooleanField(
                        default=False,
                        help_text="The ocean freight rate includes surcharges not listed separately (BAF, CAF ...)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "vendor_name",
                    "origin",
                    "destination",
                    "-valid_from",
                    "-id",
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ocean_freight", "Ocean freight"),
                            ("baf", "Bunker or fuel adjustment (BAF, LSS, ETS)"),
                            ("caf", "Currency adjustment (CAF)"),
                            ("thc_origin", "Terminal handling at origin"),
                            ("thc_destination", "Terminal handling at destination"),
                            ("documentation", "Documentation fee"),
                            ("bl_fee", "Bill of lading fee"),
                            ("security_filing", "Security filing (ISF, AMS, ENS)"),
                            ("customs_clearance", "Customs clearance"),
                            ("trucking", "Trucking or drayage"),
                            ("chassis", "Chassis"),
                            ("fuel_surcharge", "Trucking fuel surcharge"),
                            ("insurance", "Cargo insurance"),
                            ("detention", "Detention"),
                            ("demurrage", "Demurrage"),
                            ("storage", "Storage"),
                            ("per_diem", "Per diem"),
                            ("waiting_time", "Waiting time"),
                            ("redelivery", "Re-delivery or dry run"),
                            ("exam", "Customs exam or inspection"),
                            ("congestion", "Congestion or peak season surcharge"),
                            ("admin_fee", "Admin fee"),
                            ("pre_pull", "Pre-pull"),
                            ("chassis_split", "Chassis split"),
                            ("overweight", "Overweight surcharge"),
                            ("hazmat", "Hazardous cargo surcharge"),
                            ("other", "Other charge"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("container", "Per container"),
                            ("shipment", "Per shipment"),
                            ("bl", "Per bill of lading"),
                            ("kg", "Per kg"),
                            ("cbm", "Per cbm"),
                            ("day", "Per day"),
                            ("hour", "Per hour"),
                        ],
                        default="container",
                        max_length=12,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="rates.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=apps.rates.models._default_pct,
                        help_text="An overcharge is flagged only when it is more than this share of the quoted amount...",
                        max_digits=5,
                    ),
                ),
                (
                    "tolerance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=apps.rates.models._default_amount,
                        help_text="...and more than this fixed amount (home currency). The larger of the two applies.",
                        max_digits=10,
                    ),
                ),
                (
                    "warn_no_quote",
                    models.BooleanField(
                        default=True,
                        help_text="Warn when a vendor has quotes on file but none fits the shipment",
                    ),
                ),
                (
                    "check_unlisted_vendors",
                    models.BooleanField(
                        default=False,
                        help_text="Also flag extra charges from vendors with no quotes or approved extras on file",
                    ),
                ),
                (
                    "ai_classify",
                    models.BooleanField(
                        default=True,
                        help_text="Let the AI name charges the keyword table doesn't recognize (when AI reading is on)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_settings",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaughtCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        help_text="d<document id>, or s<shipment id> for shipment-wide issues",
                        max_length=40,
                    ),
                ),
                ("catch_key", models.CharField(max_length=160)),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="Validation issue code", max_length=40
                    ),
                ),
                ("charge_code", models.CharField(blank=True, max_length=30)),
                (
                    "issue_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Current validation issue; empty once the check no longer finds it",
                        null=True,
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("vendor_key", models.CharField(blank=True, max_length=200)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "amount_caught",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Largest amount flagged",
                        max_digits=14,
                    ),
                ),
                (
                    "amount_latest",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount on the latest issue",
                        max_digits=14,
                    ),
                ),
                ("first_caught_at", models.DateTimeField(db_index=True)),
                ("last_seen_at", models.DateTimeField()),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cleared_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invoice", "Invoice corrected or removed"),
                            ("rates", "Rates or checking rules changed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caught_charges",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_caught_at", "-id"],
                "unique_together": {("organization", "scope", "catch_key")},
            },
        ),
        migrations.CreateModel(
            name="ChargeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Charge name without amounts and counts",
                        max_length=200,
                    ),
                ),
                ("example", models.CharField(blank=True, max_length=200)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ocean_freight", "Ocean freight"),
                            ("baf", "Bunker or fuel adjustment (BAF, LSS, ETS)"),
                            ("caf", "Currency adjustment (CAF)"),
                            ("thc_origin", "Terminal handling at origin"),
                            ("thc_destination", "Terminal handling at destination"),
                            ("documentation", "Documentation fee"),
                            ("bl_fee", "Bill of lading fee"),
                            ("security_filing", "Security filing (ISF, AMS, ENS)"),
                            ("customs_clearance", "Customs clearance"),
                            ("trucking", "Trucking or drayage"),
                            ("chassis", "Chassis"),
                            ("fuel_surcharge", "Trucking fuel surcharge"),
                            ("insurance", "Cargo insurance"),
                            ("detention", "Detention"),
                            ("demurrage", "Demurrage"),
                            ("storage", "Storage"),
                            ("per_diem", "Per diem"),
                            ("waiting_time", "Waiting time"),
                            ("redelivery", "Re-delivery or dry run"),
                            ("exam", "Customs exam or inspection"),
                            ("congestion", "Congestion or peak season surcharge"),
                            ("admin_fee", "Admin fee"),
                            ("pre_pull", "Pre-pull"),
                            ("chassis_split", "Chassis split"),
                            ("overweight", "Overweight surcharge"),
                            ("hazmat", "Hazardous cargo surcharge"),
                            ("other", "Other charge"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "Named by AI"), ("person", "Set by a person")],
                        default="person",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_aliases",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("organization", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["organization", "vendor_key", "archived"],
                name="rates_quote_organiz_c03a42_idx",
            ),
        ),
    ]
