# Generated by Django 5.2.17 on 2026-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="e.g. shipments:read, exports:read (apps/integrations/apiscopes.py). Empty = everything the access level allows (keys made before scopes)",
            ),
        ),
    ]
