# Generated by Django 5.2.17 on 2026-10-03 12:46

import apps.customs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0006_customs_doc_types"),
        ("shipments", "0005_customs_entry_number_match"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lfd_alert_days",
                    models.PositiveSmallIntegerField(
                        default=apps.customs.models._default_lead_days,
                        help_text="Alert this many days before a container's last free day",
                    ),
                ),
                (
                    "count_weekends",
                    models.BooleanField(
                        default=False,
                        help_text="Count Saturdays, Sundays and holidays as free days when a notice doesn't say how its free days are counted",
                    ),
                ),
                (
                    "holidays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Public holidays (YYYY-MM-DD) that are not counted as free days",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs_settings",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerFreeTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_number", models.CharField(max_length=15)),
                ("carrier_name", models.CharField(blank=True, max_length=200)),
                ("terminal", models.CharField(blank=True, max_length=200)),
                ("eta", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "discharge_estimated",
                    models.BooleanField(
                        default=False,
                        help_text="No discharge or arrival date printed: counted from the ETA",
                    ),
                ),
                (
                    "demurrage_free_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "detention_free_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "count_weekends",
                    models.BooleanField(
                        default=False,
                        help_text="Weekends and holidays count as free days",
                    ),
                ),
                (
                    "basis_note",
                    models.CharField(
                        blank=True,
                        help_text="How free days are counted, and why",
                        max_length=200,
                    ),
                ),
                (
                    "detention_from",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup from the terminal"),
                            ("discharge", "Discharge from the vessel"),
                        ],
                        default="pickup",
                        max_length=10,
                    ),
                ),
                (
                    "lfd_demurrage",
                    models.DateField(
                        blank=True, help_text="Last free day at the terminal", null=True
                    ),
                ),
                ("lfd_demurrage_printed", models.BooleanField(default=False)),
                (
                    "lfd_detention",
                    models.DateField(
                        blank=True,
                        help_text="Last free day to return the empty",
                        null=True,
                    ),
                ),
                ("lfd_detention_printed", models.BooleanField(default=False)),
                ("picked_up_on", models.DateField(blank=True, null=True)),
                ("returned_on", models.DateField(blank=True, null=True)),
                ("alerted_demurrage_soon", models.DateField(blank=True, null=True)),
                ("alerted_demurrage_late", models.DateField(blank=True, null=True)),
                ("alerted_detention_soon", models.DateField(blank=True, null=True)),
                ("alerted_detention_late", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Latest arrival notice for this container",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_time",
                        to="core.organization",
                    ),
                ),
                (
                    "picked_up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_time",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["lfd_demurrage", "container_number", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "returned_on"],
                        name="customs_con_organiz_4f98b1_idx",
                    )
                ],
                "unique_together": {("shipment", "container_number")},
            },
        ),
        migrations.CreateModel(
            name="HtsReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hts_code", models.CharField(max_length=12)),
                ("description_key", models.CharField(max_length=200)),
                ("plausible", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hts_reviews",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "hts_code", "description_key")},
            },
        ),
    ]
