# Generated by Django 5.2.17 on 2026-10-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True, help_text="Key in BILLING_PLANS", max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Free trial"),
                            ("active", "Active"),
                            ("past_due", "Payment overdue"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "stripe_status",
                    models.CharField(
                        blank=True,
                        help_text="Subscription status as Stripe reports it",
                        max_length=30,
                    ),
                ),
                (
                    "stripe_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time of the newest Stripe subscription state applied (older events are ignored)",
                        null=True,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "soft_notice_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the billing month whose 100% email was sent",
                        null=True,
                    ),
                ),
                (
                    "hard_notice_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the billing month whose paused-intake email was sent",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "nonce",
                    models.CharField(
                        help_text="Part of the emailed link; a new sign-up gets a new one",
                        max_length=32,
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=40)),
                ("emails_sent", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=80, unique=True)),
                ("type", models.CharField(max_length=80)),
                (
                    "created",
                    models.DateTimeField(help_text="When Stripe created the event"),
                ),
                ("livemode", models.BooleanField(default=False)),
                ("outcome", models.CharField(blank=True, max_length=300)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_events",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
    ]
