# Generated by Django 5.2.17 on 2026-10-03 12:53

import apps.core.crypto
import apps.integrations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    apps.core.crypto.EncryptedTextField(
                        help_text="https address (encrypted: it may carry a token)"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Event types this endpoint receives",
                    ),
                ),
                (
                    "secret",
                    apps.core.crypto.EncryptedTextField(
                        help_text="Signing secret (whsec_...), shown once"
                    ),
                ),
                ("previous_secret", apps.core.crypto.EncryptedTextField(blank=True)),
                (
                    "previous_secret_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_reason", models.CharField(blank=True, max_length=300)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        default=apps.integrations.models.new_event_id,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=60)),
                ("payload", models.JSONField(default=dict)),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to send"),
                            ("sending", "Sending"),
                            ("retrying", "Will retry"),
                            ("succeeded", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True, help_text="The first part of the answer"
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_test", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replay_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replays",
                        to="integrations.webhookdelivery",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhookendpoint",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhookevent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IssueAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.PositiveBigIntegerField()),
                ("fingerprint", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("shipment_id", "fingerprint")},
            },
        ),
    ]
