# Generated by Django 5.2.17 on 2026-10-03 10:46

import apps.core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0003_llm_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inbound", "Forwarding address"),
                            ("microsoft", "Microsoft 365"),
                            ("imap", "IMAP"),
                            ("gmail", "Gmail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="The mailbox's email address",
                        max_length=320,
                    ),
                ),
                (
                    "inbound_local",
                    models.CharField(
                        blank=True,
                        help_text="Local part of the forwarding address (before the @); the random part makes it unguessable",
                        max_length=80,
                        null=True,
                        unique=True,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("ssl", "SSL/TLS (usually port 993)"),
                            ("starttls", "STARTTLS (usually port 143)"),
                        ],
                        default="ssl",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=320)),
                ("password", apps.core.crypto.EncryptedTextField(blank=True)),
                ("access_token", apps.core.crypto.EncryptedTextField(blank=True)),
                ("refresh_token", apps.core.crypto.EncryptedTextField(blank=True)),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "folder",
                    models.CharField(
                        blank=True,
                        help_text="IMAP folder name, Microsoft folder ID or Gmail label",
                        max_length=255,
                    ),
                ),
                ("folder_name", models.CharField(blank=True, max_length=255)),
                (
                    "folder_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Folders offered in the settings (Microsoft 365)",
                    ),
                ),
                (
                    "after_import",
                    models.CharField(
                        choices=[
                            ("category", "Add the ShipMatch category"),
                            ("move", "Move it to another folder"),
                            ("category_move", "Add the category and move it"),
                            ("none", "Leave it as it is"),
                        ],
                        default="category",
                        max_length=20,
                    ),
                ),
                ("processed_folder", models.CharField(blank=True, max_length=255)),
                ("processed_folder_name", models.CharField(blank=True, max_length=255)),
                (
                    "mark_seen",
                    models.BooleanField(
                        default=False, help_text="IMAP: mark imported emails as read"
                    ),
                ),
                (
                    "allowed_senders",
                    models.TextField(
                        blank=True,
                        help_text="Only accept email from these addresses or domains (one per line). Empty = anyone.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("needs_reconnect", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_received_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("cursor", models.CharField(blank=True, max_length=2000)),
                (
                    "cursor_validity",
                    models.CharField(
                        blank=True,
                        help_text="IMAP UIDVALIDITY the cursor belongs to",
                        max_length=40,
                    ),
                ),
                ("emails_received", models.PositiveIntegerField(default=0)),
                ("documents_received", models.PositiveIntegerField(default=0)),
                ("attachments_skipped", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MailboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mailbox_name",
                    models.CharField(
                        blank=True,
                        help_text="Kept when the mailbox is removed",
                        max_length=160,
                    ),
                ),
                (
                    "mailbox_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inbound", "Forwarding address"),
                            ("microsoft", "Microsoft 365"),
                            ("imap", "IMAP"),
                            ("gmail", "Gmail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=320)),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        help_text="UID, Microsoft or provider message ID",
                        max_length=255,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("documents", "Documents added"),
                            ("duplicates", "Files received before"),
                            ("nothing", "No documents in it"),
                            ("blocked", "Sender not allowed"),
                            ("failed", "Couldn't be processed"),
                        ],
                        default="nothing",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("documents_created", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake",
                        to="documents.ingestedemail",
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="mailboxes.mailbox",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox_messages",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=150)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("imported", "Added as a document"),
                            ("duplicate", "Same file received before"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_attachments",
                        to="documents.document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mailboxes.mailboxmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="mailbox",
            index=models.Index(
                fields=["enabled", "kind"], name="mailboxes_m_enabled_eba1c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "inbound")),
                fields=("organization",),
                name="mailbox_one_forwarding_address_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxmessage",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="mailboxes_m_organiz_708d54_idx",
            ),
        ),
    ]
