# Generated by Django 5.2.17 on 2026-10-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0003_llm_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_key", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("commercial_invoice", "Commercial invoice"),
                            ("bill_of_lading", "Bill of lading"),
                            ("freight_invoice", "Freight invoice"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("labels", models.JSONField(blank=True, default=dict)),
                (
                    "date_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not learned yet"),
                            ("dmy", "Day first (DD/MM/YYYY)"),
                            ("mdy", "Month first (MM/DD/YYYY)"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "date_votes",
                    models.JSONField(
                        blank=True, default=dict, help_text='{"dmy": 2, "mdy": 0}'
                    ),
                ),
                (
                    "field_corrections",
                    models.JSONField(
                        blank=True, default=dict, help_text="Corrections per field"
                    ),
                ),
                (
                    "examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Most recent corrections, newest last",
                    ),
                ),
                ("correction_count", models.PositiveIntegerField(default=0)),
                ("last_learned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profiles",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "doc_type"],
                "unique_together": {("organization", "vendor_key", "doc_type")},
            },
        ),
        migrations.CreateModel(
            name="DocumentLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("corrections_at_read", models.PositiveIntegerField(default=0)),
                ("fields", models.JSONField(blank=True, default=dict)),
                (
                    "hint_chars",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Size of the vendor notes sent to the AI reader",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_record",
                        to="documents.document",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="learning.vendorprofile",
                    ),
                ),
            ],
        ),
    ]
