# Generated by Django 5.2.17 on 2026-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_learning_vendor_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("commercial_invoice", "Commercial invoice"),
                    ("bill_of_lading", "Bill of lading"),
                    ("freight_invoice", "Freight invoice"),
                    ("credit_note", "Credit note"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
