# Generated by Django 5.2.17 on 2026-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_learning_credit_note_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("commercial_invoice", "Commercial invoice"),
                    ("bill_of_lading", "Bill of lading"),
                    ("freight_invoice", "Freight invoice"),
                    ("credit_note", "Credit note"),
                    ("customs_entry", "Customs entry"),
                    ("arrival_notice", "Arrival notice"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
