# Generated by Django 5.2.17 on 2026-10-03 12:57

import apps.close.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0005_evidence_field_location"),
        ("shipments", "0004_intake_credit_match"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accrued_account",
                    models.CharField(
                        default=apps.close.models._accrued_default,
                        help_text="Account credited by the accrual (a liability account)",
                        max_length=200,
                    ),
                ),
                (
                    "accrued_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Its QuickBooks account ID, if known",
                        max_length=40,
                    ),
                ),
                (
                    "freight_account",
                    models.CharField(
                        default=apps.close.models._freight_default,
                        help_text="Account debited for freight when the vendor has no account set",
                        max_length=200,
                    ),
                ),
                (
                    "goods_account",
                    models.CharField(
                        default=apps.close.models._goods_default,
                        help_text="Account debited for supplier (goods) invoices without an account set",
                        max_length=200,
                    ),
                ),
                (
                    "include_goods",
                    models.BooleanField(
                        default=True,
                        help_text="Also accrue supplier (goods) invoices received but not booked, debited to the goods account",
                    ),
                ),
                (
                    "expect_freight",
                    models.CharField(
                        choices=[
                            ("always", "Every shipment"),
                            ("usual", "When most similar shipments have it"),
                            ("never", "Never"),
                        ],
                        default="always",
                        max_length=10,
                    ),
                ),
                (
                    "expect_destination",
                    models.CharField(
                        choices=[
                            ("always", "Every shipment"),
                            ("usual", "When most similar shipments have it"),
                            ("never", "Never"),
                        ],
                        default="always",
                        max_length=10,
                    ),
                ),
                (
                    "expect_delivery",
                    models.CharField(
                        choices=[
                            ("always", "Every shipment"),
                            ("usual", "When most similar shipments have it"),
                            ("never", "Never"),
                        ],
                        default="usual",
                        max_length=10,
                    ),
                ),
                (
                    "lookback_days",
                    models.PositiveIntegerField(
                        default=apps.close.models._lookback_default,
                        help_text="Shipments that shipped longer ago than this before the period end are listed, not accrued",
                    ),
                ),
                (
                    "min_history",
                    models.PositiveSmallIntegerField(
                        default=apps.close.models._history_default,
                        help_text="Past invoices needed before a median is used as an estimate",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_settings",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=200)),
                ("vendor_key", models.CharField(db_index=True, max_length=200)),
                ("paid_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(max_length=3)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Check, wire or payment number",
                        max_length=100,
                    ),
                ),
                (
                    "allocations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Invoices it paid: [{"document_id", "invoice_number", "amount"}]',
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered by a person"),
                            ("quickbooks", "QuickBooks"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("qbo_id", models.CharField(blank=True, max_length=40)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payments",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                (
                    "vendor_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Balance printed on the statement",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=apps.close.models.statement_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "source_format",
                    models.CharField(help_text="pdf, xlsx or csv", max_length=12),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "reader",
                    models.CharField(
                        blank=True,
                        help_text="rules, or the AI provider that read it",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="What the reader could not read, for the reviewer",
                    ),
                ),
                ("llm_usage", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Reconciled"),
                            ("needs_vendor", "Choose the vendor"),
                            ("unreadable", "Couldn't be read"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Balances and differences from the last match",
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_statements",
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("credit", "Credit note"),
                            ("payment", "Payment"),
                            ("opening", "Opening balance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=80)),
                ("date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("raw", models.CharField(blank=True, max_length=500)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="close.vendorstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReconItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("amount_differs", "Amount differs"),
                            ("missing", "On the statement, never received"),
                            ("not_on_statement", "Received, not on the statement"),
                            ("credit_not_applied", "Credit notes not applied"),
                            ("duplicate", "Possible duplicates on the statement"),
                            (
                                "payment_not_applied",
                                "Payments the vendor hasn't applied",
                            ),
                            ("payment_unknown", "Payments ShipMatch has no record of"),
                            ("settled", "Paid and closed"),
                            ("opening", "Opening balance differs"),
                            ("arithmetic", "Statement doesn't add up"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=200)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Invoice, credit note or payment it is about",
                        max_length=200,
                    ),
                ),
                (
                    "statement_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "shipmatch_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "effect",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("explanation", models.CharField(blank=True, max_length=600)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="close.statementline",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="close.vendorpayment",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="close.vendorstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccrualAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("exclude", "Don't accrue"),
                            ("amount", "Use this amount"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("note", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_adjustments",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_adjustments",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "unique_together": {("organization", "shipment", "group")},
            },
        ),
        migrations.CreateModel(
            name="AccrualSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_end", models.DateField()),
                ("version", models.PositiveIntegerField()),
                (
                    "report",
                    models.JSONField(
                        help_text="Every line, total and setting as shown when locked"
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(max_length=3)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 of the stored report, to show it was not altered",
                        max_length=64,
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_snapshots",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-version"],
                "unique_together": {("organization", "period_end", "version")},
            },
        ),
        migrations.AddConstraint(
            model_name="vendorpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("qbo_id", ""), _negated=True),
                fields=("organization", "qbo_id"),
                name="close_payment_unique_qbo_id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorstatement",
            unique_together={("organization", "sha256")},
        ),
        migrations.AlterUniqueTogether(
            name="reconitem",
            unique_together={("statement", "fingerprint")},
        ),
    ]
