# Generated by Django 5.2.17 on 2026-10-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0005_evidence_field_location"),
        ("shipments", "0004_intake_credit_match"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandedCostRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of",
                    models.DateField(
                        help_text="Date of the goods (commercial invoice date, else B/L date)"
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "goods_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "charges_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "landed_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=True,
                        help_text="False when products or exchange rates were missing",
                    ),
                ),
                ("policy", models.JSONField(blank=True, default=dict)),
                ("notes", models.JSONField(blank=True, default=list)),
                (
                    "charges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Each charge and how it was spread",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_runs",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_run",
                        to="shipments.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandedCostLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product_key",
                    models.CharField(
                        db_index=True,
                        help_text="Supplier + SKU (or description)",
                        max_length=260,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=60)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("hs_code", models.CharField(blank=True, max_length=20)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=16, null=True
                    ),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                ("goods_value", models.DecimalField(decimal_places=2, max_digits=16)),
                ("charges", models.DecimalField(decimal_places=2, max_digits=16)),
                ("by_category", models.JSONField(blank=True, default=dict)),
                ("landed_total", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("as_of", models.DateField(db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="landed.landedcostrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="LandedSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("value", "By value"),
                            ("quantity", "By quantity"),
                            ("weight", "By weight"),
                            ("volume", "By volume"),
                        ],
                        default="value",
                        max_length=12,
                    ),
                ),
                (
                    "by_category",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Method per type of charge, e.g. {"freight": "volume", "duty": "value"}',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_settings",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharedInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Shared"), ("dismissed", "Not shared")],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("lines", "By the lines that name each shipment"),
                            ("equal", "Equally"),
                            ("containers", "By number of containers"),
                            ("weight", "By weight"),
                            ("volume", "By volume"),
                            ("manual", "Amounts typed by a reviewer"),
                        ],
                        default="containers",
                        max_length=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "detected",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="References found on the invoice per shipment, approved shipments it names, notes from the split",
                    ),
                ),
                (
                    "confirmed_hash",
                    models.CharField(
                        blank=True,
                        help_text="The split a person confirmed",
                        max_length=40,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_invoice",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_invoices",
                        to="core.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentLandedOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("value", "By value"),
                            ("quantity", "By quantity"),
                            ("weight", "By weight"),
                            ("volume", "By volume"),
                        ],
                        default="value",
                        max_length=12,
                    ),
                ),
                ("by_category", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_override",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("lines", "By the lines that name each shipment"),
                            ("equal", "Equally"),
                            ("containers", "By number of containers"),
                            ("weight", "By weight"),
                            ("volume", "By volume"),
                            ("manual", "Amounts typed by a reviewer"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_allocations",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_shares",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "shipment"),
                        name="landed_one_share_per_shipment",
                    )
                ],
            },
        ),
    ]
