# Generated by Django 5.2.17 on 2026-10-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="auditevent",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="membership",
            name="approval_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Largest shipment total (home currency) this person may approve. Empty = no limit.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="fx_rates",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Home-currency value of one unit of each foreign currency, e.g. {"EUR": "1.08"}',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="maker_checker",
            field=models.BooleanField(
                default=True,
                help_text="A person who edited a shipment cannot approve it",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="require_mfa",
            field=models.BooleanField(
                default=False,
                help_text="Every member must use two-factor authentication",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="review_threshold",
            field=models.FloatField(
                blank=True,
                help_text="Fields below this confidence go to review (default from settings)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Used for dates when a user's own time zone is unknown",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("reviewer", "Reviewer"),
                    ("approver", "Approver"),
                    ("admin", "Admin"),
                ],
                default="reviewer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="core_audite_organiz_8bd346_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="core_audite_object__bbabc4_idx",
            ),
        ),
    ]
