# Generated by Django 5.1.15 on 2026-10-01 15:44

import apps.core.crypto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostedBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="QuickBooks idempotency key",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("qbo_bill_id", models.CharField(blank=True, max_length=40)),
                ("qbo_attachable_id", models.CharField(blank=True, max_length=40)),
                ("error", models.TextField(blank=True)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_bill",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_bills",
                        to="core.organization",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_bills",
                        to="shipments.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QBOConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("realm_id", models.CharField(max_length=40)),
                ("access_token", apps.core.crypto.EncryptedTextField()),
                ("refresh_token", apps.core.crypto.EncryptedTextField()),
                ("access_expires_at", models.DateTimeField()),
                ("refresh_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_expense_account_id",
                    models.CharField(
                        blank=True,
                        help_text="QuickBooks account used when a vendor has no mapping",
                        max_length=40,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qbo",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_key", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("qbo_vendor_id", models.CharField(blank=True, max_length=40)),
                ("expense_account_id", models.CharField(blank=True, max_length=40)),
                ("expense_account_name", models.CharField(blank=True, max_length=200)),
                ("learned_from_correction", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_mappings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "vendor_key")},
            },
        ),
    ]
