# Generated by Django 5.2.17 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qboconnection",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="qboconnection",
            name="home_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="qboconnection",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qboconnection",
            name="multicurrency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qboconnection",
            name="needs_reconnect",
            field=models.BooleanField(
                default=False,
                help_text="Intuit rejected the refresh token; an admin must connect again",
            ),
        ),
    ]
