# Generated by Django 5.2.17 on 2026-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_connection_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="postedbill",
            name="kind",
            field=models.CharField(
                choices=[("bill", "Bill"), ("vendor_credit", "Vendor credit")],
                default="bill",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postedbill",
            name="qbo_bill_id",
            field=models.CharField(
                blank=True,
                help_text="QuickBooks Bill or VendorCredit Id",
                max_length=40,
            ),
        ),
    ]
