# Generated by Django 5.2.17 on 2026-10-03 12:54

import apps.core.crypto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_intake_vendor_credit"),
        ("core", "0003_assign_admins"),
        ("documents", "0005_evidence_field_location"),
        ("shipments", "0004_intake_credit_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_auto_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last scheduled check (at most hourly)",
                        null=True,
                    ),
                ),
                (
                    "running_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set while a check runs, so two never overlap",
                        null=True,
                    ),
                ),
                (
                    "paused_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Daily API limit reached: wait until then",
                        null=True,
                    ),
                ),
                ("last_summary", models.JSONField(blank=True, default=dict)),
                ("last_error", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="XeroConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero organisation (tenant) bills post to",
                        max_length=64,
                    ),
                ),
                ("tenant_name", models.CharField(blank=True, max_length=200)),
                (
                    "connection_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero connection id for this tenant",
                        max_length=64,
                    ),
                ),
                (
                    "tenants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Organisations this sign-in can reach: [{id, tenantId, tenantName}]",
                    ),
                ),
                ("access_token", apps.core.crypto.EncryptedTextField()),
                ("refresh_token", apps.core.crypto.EncryptedTextField()),
                ("access_expires_at", models.DateTimeField()),
                ("refresh_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_account_code",
                    models.CharField(
                        blank=True,
                        help_text="Xero account code used when a vendor has no rule",
                        max_length=20,
                    ),
                ),
                (
                    "bill_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (approve in Xero)"),
                            ("AUTHORISED", "Awaiting payment (approved)"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "home_currency",
                    models.CharField(
                        blank=True, help_text="Xero base currency", max_length=3
                    ),
                ),
                (
                    "currencies",
                    models.JSONField(
                        blank=True, default=list, help_text="Currencies added in Xero"
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        help_text="Xero organisation short code (for links)",
                        max_length=20,
                    ),
                ),
                (
                    "needs_reconnect",
                    models.BooleanField(
                        default=False,
                        help_text="Xero rejected the refresh token; an admin must connect again",
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="postedbill",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Still to pay, or for a credit: not used yet",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Paid, or for a credit: used against bills",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="amount_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="external_number",
            field=models.CharField(
                blank=True,
                help_text="Bill number shown in the accounting system",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="ledger_id",
            field=models.CharField(
                blank=True,
                help_text="QuickBooks company (realm) or Xero organisation (tenant) it was posted to",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="paid_on",
            field=models.DateField(
                blank=True, help_text="Date of the payment that settled it", null=True
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="payment_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="payment_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="payment_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partly_paid", "Partly paid"),
                    ("paid", "Paid"),
                    ("voided", "Voided"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="payments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{date, amount, kind: payment|credit, reference}] as the system reports them",
            ),
        ),
        migrations.AddField(
            model_name="postedbill",
            name="system",
            field=models.CharField(
                choices=[("quickbooks", "QuickBooks"), ("xero", "Xero")],
                default="quickbooks",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="vendormapping",
            name="xero_account_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendormapping",
            name="xero_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vendormapping",
            name="xero_contact_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="postedbill",
            name="qbo_attachable_id",
            field=models.CharField(
                blank=True, help_text="ID of the attached PDF", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="postedbill",
            name="qbo_bill_id",
            field=models.CharField(
                blank=True,
                help_text="ID in the accounting system: QuickBooks Bill or VendorCredit Id, Xero InvoiceID or CreditNoteID",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="postedbill",
            name="request_id",
            field=models.CharField(
                help_text="Idempotency key (QuickBooks requestid, Xero Idempotency-Key)",
                max_length=60,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="postedbill",
            index=models.Index(
                fields=["organization", "status", "payment_status"],
                name="accounting__organiz_8f58a4_idx",
            ),
        ),
        migrations.AddField(
            model_name="paymentsync",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_sync",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="xeroconnection",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xero",
                to="core.organization",
            ),
        ),
    ]
