# Generated by Django 5.2.17 on 2026-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_xero_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="xeroconnection",
            name="previous_tenant_id",
            field=models.CharField(
                blank=True,
                help_text="Organisation bills went to before a new sign-in; cleared once one is chosen",
                max_length=64,
            ),
        ),
    ]
