# Generated by Django 5.1.15 on 2026-10-01 15:44

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("sender", models.CharField(blank=True, max_length=320)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("attachment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "message_id")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("upload", "Upload"),
                            ("folder", "Folder import"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=apps.documents.models.upload_path)),
                ("sha256", models.CharField(max_length=64)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("text", models.TextField(blank=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("commercial_invoice", "Commercial invoice"),
                            ("bill_of_lading", "Bill of lading"),
                            ("freight_invoice", "Freight invoice"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("classification_confidence", models.FloatField(default=0.0)),
                ("extraction_provider", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("needs_ocr", "Needs OCR"),
                            ("extracted", "Extracted"),
                            ("matched", "Matched to shipment"),
                            ("unmatched", "No shipment found"),
                            ("error", "Processing error"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.organization",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.ingestedemail",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at", "id"],
                "unique_together": {("organization", "sha256")},
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "grounded",
                    models.BooleanField(
                        default=False,
                        help_text="Value was found verbatim in the document text",
                    ),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rules", "Rule extractor"),
                            ("llm", "LLM"),
                            ("human", "Human correction"),
                        ],
                        default="rules",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("document", "name")},
            },
        ),
    ]
