# Generated by Django 5.1.15 on 2026-10-01 15:53

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=apps.documents.models.upload_path
            ),
        ),
    ]
