# Generated by Django 5.2.17 on 2026-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_file_path_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="llm_usage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tokens, time and estimated cost of AI calls",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="text_source",
            field=models.CharField(
                blank=True,
                help_text="text_layer, anthropic, textract or none",
                max_length=20,
            ),
        ),
    ]
