# Generated by Django 5.2.17 on 2026-10-03 10:50

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_llm_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="intake",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="How the file was received: conversion, archive contents, split pages",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="The file exactly as received, when it is not a PDF",
                max_length=500,
                upload_to=apps.documents.models.original_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The ZIP archive or multi-invoice PDF this document came from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_format",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("spreadsheet", "Spreadsheet"),
                    ("archive", "ZIP archive"),
                ],
                default="pdf",
                help_text="What was received; images and spreadsheets are converted to a PDF copy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("commercial_invoice", "Commercial invoice"),
                    ("bill_of_lading", "Bill of lading"),
                    ("freight_invoice", "Freight invoice"),
                    ("credit_note", "Credit note"),
                    ("other", "Other"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("needs_ocr", "Needs OCR"),
                    ("extracted", "Extracted"),
                    ("matched", "Matched to shipment"),
                    ("unmatched", "No shipment found"),
                    ("error", "Processing error"),
                    ("split", "Split into separate documents"),
                    ("archive", "Archive unpacked"),
                ],
                db_index=True,
                default="received",
                max_length=20,
            ),
        ),
    ]
