# Generated by Django 5.2.17 on 2026-10-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_intake_formats_credit_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedfield",
            name="location",
            field=models.JSONField(
                blank=True,
                help_text="Where the value is printed: {status, page, boxes: [[x0, top, x1, bottom]] as 0..1 of the page, score, items} (see apps/documents/services/locate.py)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OcrLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="textract", max_length=20)),
                (
                    "words",
                    models.JSONField(
                        default=list,
                        help_text="[[page, x0, top, x1, bottom, text], ...] with 0..1 coordinates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_layout",
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
