# Generated by Django 5.2.17 on 2026-10-03 10:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_assign_admins"),
        ("documents", "0003_llm_usage"),
        ("shipments", "0003_issue_amount_at_risk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "shipment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Kept if the shipment is removed",
                        max_length=20,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=60)),
                ("vendor_name", models.CharField(max_length=200)),
                ("vendor_key", models.CharField(db_index=True, max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("vendor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "cc",
                    models.CharField(
                        blank=True,
                        help_text="Extra recipients, separated by commas",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to vendor"),
                            ("acknowledged", "Vendor acknowledged"),
                            ("credit_received", "Credit received"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed without recovery"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "amount_disputed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount_recovered",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount_recovered_home",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recovered amount in the home currency at the rate set when the credit was recorded",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "recovered_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("subject", models.CharField(blank=True, max_length=250)),
                ("body", models.TextField(blank=True)),
                ("ai_polished", models.BooleanField(default=False)),
                ("message_id", models.CharField(blank=True, max_length=250)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_on", models.DateField(blank=True, null=True)),
                (
                    "overdue_flagged_for",
                    models.DateField(
                        blank=True,
                        help_text="Follow-up date that was last reported as overdue",
                        null=True,
                    ),
                ),
                ("hold_released", models.BooleanField(default=False)),
                ("hold_released_at", models.DateTimeField(blank=True, null=True)),
                ("hold_release_note", models.CharField(blank=True, max_length=500)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credited_disputes",
                        to="documents.document",
                    ),
                ),
                (
                    "hold_released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="core.organization",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Draft created"),
                            ("sent", "Sent to vendor"),
                            ("send_failed", "Sending failed"),
                            ("reply", "Vendor reply logged"),
                            ("credit", "Credit linked"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed without recovery"),
                            ("released", "Shipment released for approval"),
                            ("follow_up", "Follow-up date changed"),
                            ("overdue", "Follow-up date passed"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="disputes.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DisputeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=200)),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                (
                    "explanation",
                    models.TextField(
                        help_text="What is wrong, in words the vendor understands"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_items",
                        to="shipments.validationissue",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DisputeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True,
                        help_text="Accounts payable mailbox that vendor replies go to",
                        max_length=254,
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True, help_text="Closing lines of every dispute email"
                    ),
                ),
                ("follow_up_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "copy_reply_to",
                    models.BooleanField(
                        default=True,
                        help_text="Send a copy of each dispute to the reply-to mailbox",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_settings",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_key", models.CharField(max_length=200)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_contacts",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["organization", "status"], name="disputes_di_organiz_838af8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorcontact",
            unique_together={("organization", "vendor_key")},
        ),
    ]
