# Generated by Django 5.2.17 on 2026-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationissue",
            name="resolution_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="matchlink",
            name="method",
            field=models.CharField(
                choices=[
                    ("exact_bl", "Exact B/L number"),
                    ("exact_container", "Exact container number"),
                    ("exact_po", "Exact PO number"),
                    ("fuzzy", "Near-match reference"),
                    ("new_shipment", "First document of this shipment"),
                    ("manual", "Assigned by reviewer"),
                ],
                max_length=20,
            ),
        ),
    ]
