# Generated by Django 5.2.17 on 2026-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_resolution_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationissue",
            name="amount_at_risk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Money this issue would cost if paid as invoiced (overcharge, duplicate, unapproved charge)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="validationissue",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
