# Generated by Django 5.2.17 on 2026-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_issue_amount_at_risk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchlink",
            name="method",
            field=models.CharField(
                choices=[
                    ("exact_bl", "Exact B/L number"),
                    ("exact_container", "Exact container number"),
                    ("exact_po", "Exact PO number"),
                    ("fuzzy", "Near-match reference"),
                    ("original_invoice", "Invoice it credits"),
                    ("new_shipment", "First document of this shipment"),
                    ("manual", "Assigned by reviewer"),
                ],
                max_length=20,
            ),
        ),
    ]
